sudo: required 

services:
  - docker

before_install:
  - docker build -t pacrob/docker-react -f Dockerfile.dev .

script:
  - docker run pacrob/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pacrob-docker-react"
  env: "PacrobDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-344378332628"
  bucket_path: "pacrob-docker-react"
  on:
    branch: master
  access_key_id: "$aws_access_key"
  secret_access_key:
    secure: "$aws_secret_key"

